import PDFDocument from 'pdfkit';
import { Chapter } from '../models';

interface ExportOptions {
  title: string;
  author: string;
  genre?: string;
  projectFormat?: 'novel' | 'screenplay' | 'short_story';
  chapters: { title: string; content: string; order: number }[];
  format: 'pdf' | 'docx';
}

function stripHtml(html: string): string {
  return html
    .replace(/<h[1-6][^>]*>(.*?)<\/h[1-6]>/gi, '\n$1\n\n')
    .replace(/<p[^>]*>(.*?)<\/p>/gi, '$1\n\n')
    .replace(/<br\s*\/?>/gi, '\n')
    .replace(/<[^>]+>/g, '')
    .replace(/&nbsp;/g, ' ')
    .replace(/&amp;/g, '&')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/\n{3,}/g, '\n\n')
    .trim();
}

export function generatePdf(options: ExportOptions): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    try {
      const doc = new PDFDocument({
        size: 'A4',
        margins: { top: 72, bottom: 72, left: 72, right: 72 },
        info: {
          Title: options.title,
          Author: options.author,
        },
      });

      const chunks: Buffer[] = [];
      doc.on('data', (chunk: Buffer) => chunks.push(chunk));
      doc.on('end', () => resolve(Buffer.concat(chunks)));
      doc.on('error', reject);

      // Title page
      doc.moveDown(8);
      doc.fontSize(28).font('Helvetica-Bold').text(options.title, { align: 'center' });
      doc.moveDown(0.5);
      if (options.projectFormat === 'short_story') {
        doc.fontSize(14).font('Helvetica-Oblique').text('A Short Story', { align: 'center' });
      }
      doc.moveDown(0.5);
      doc.fontSize(16).font('Helvetica').text(`by ${options.author}`, { align: 'center' });
      if (options.genre) {
        doc.moveDown(0.5);
        doc.fontSize(12).font('Helvetica-Oblique').text(options.genre, { align: 'center' });
      }
      doc.moveDown(2);
      doc.fontSize(10).font('Helvetica').text(`Generated by Narratica`, { align: 'center' });

      // Chapters
      const sortedChapters = [...options.chapters].sort((a, b) => a.order - b.order);

      for (const chapter of sortedChapters) {
        doc.addPage();

        // Chapter title
        doc.fontSize(20).font('Helvetica-Bold').text(chapter.title, { align: 'center' });
        doc.moveDown(2);

        // Chapter content
        const text = stripHtml(chapter.content);
        if (text) {
          doc.fontSize(12).font('Times-Roman').text(text, {
            align: 'justify',
            lineGap: 4,
            paragraphGap: 8,
          });
        } else {
          doc.fontSize(12).font('Times-Italic').text('(No content yet)', { align: 'center' });
        }
      }

      doc.end();
    } catch (error) {
      reject(error);
    }
  });
}

export function generateDocx(options: ExportOptions): Buffer {
  // Simple DOCX-compatible HTML that Word can open
  const sortedChapters = [...options.chapters].sort((a, b) => a.order - b.order);

  let html = `<!DOCTYPE html>
<html xmlns:o="urn:schemas-microsoft-com:office:office"
      xmlns:w="urn:schemas-microsoft-com:office:word"
      xmlns="http://www.w3.org/TR/REC-html40">
<head>
<meta charset="utf-8">
<title>${escapeHtml(options.title)}</title>
<style>
  body { font-family: 'Times New Roman', serif; font-size: 12pt; line-height: 1.6; margin: 1in; }
  h1 { font-family: Arial, sans-serif; font-size: 28pt; text-align: center; page-break-before: always; margin-top: 3in; }
  h1.title-page { margin-top: 4in; page-break-before: auto; }
  h2 { font-family: Arial, sans-serif; font-size: 20pt; text-align: center; page-break-before: always; margin-bottom: 2em; }
  .author { font-size: 16pt; text-align: center; margin-top: 1em; }
  .genre { font-size: 12pt; text-align: center; font-style: italic; margin-top: 0.5em; }
  .meta { font-size: 10pt; text-align: center; margin-top: 2em; color: #666; }
  p { text-align: justify; margin-bottom: 0.5em; }
</style>
</head>
<body>
  <h1 class="title-page">${escapeHtml(options.title)}</h1>
  ${options.projectFormat === 'short_story' ? `<p class="genre">A Short Story</p>` : ''}
  <p class="author">by ${escapeHtml(options.author)}</p>
  ${options.genre ? `<p class="genre">${escapeHtml(options.genre)}</p>` : ''}
  <p class="meta">Generated by Narratica</p>
`;

  for (const chapter of sortedChapters) {
    html += `  <h2>${escapeHtml(chapter.title)}</h2>\n`;
    const text = stripHtml(chapter.content);
    if (text) {
      const paragraphs = text.split('\n\n').filter(Boolean);
      for (const p of paragraphs) {
        html += `  <p>${escapeHtml(p)}</p>\n`;
      }
    } else {
      html += `  <p><em>(No content yet)</em></p>\n`;
    }
  }

  html += `</body>\n</html>`;
  return Buffer.from(html, 'utf-8');
}

// ── Fountain (screenplay) export ──────────────────────────
// Fountain is a plain-text markup format for screenplays
// Spec: https://fountain.io/syntax
export function generateFountain(options: ExportOptions): Buffer {
  const sortedChapters = [...options.chapters].sort((a, b) => a.order - b.order);

  let fountain = `Title: ${options.title}\nCredit: Written by\nAuthor: ${options.author}\nDraft date: ${new Date().toLocaleDateString()}\nContact: Generated by Narratica\n\n`;

  for (const chapter of sortedChapters) {
    fountain += `===\n\n`; // Page break in Fountain

    if (!chapter.content) continue;

    // Parse the HTML from the screenplay editor into Fountain syntax
    const lines = chapter.content
      .replace(/<br\s*\/?>/gi, '\n')
      .split(/<\/div>|<\/p>/)
      .map((line) => line.trim())
      .filter(Boolean);

    for (const line of lines) {
      // Detect element type by CSS class
      const text = line
        .replace(/<[^>]+>/g, '')
        .replace(/&nbsp;/g, ' ')
        .replace(/&amp;/g, '&')
        .replace(/&lt;/g, '<')
        .replace(/&gt;/g, '>')
        .replace(/&quot;/g, '"')
        .replace(/&#39;/g, "'")
        .trim();

      if (!text) continue;

      if (line.includes('screenplay-scene-heading')) {
        // Scene headings: must start with INT., EXT., etc. or force with .
        if (/^(INT|EXT|EST|INT\.\/EXT|I\/E)[\.\s]/i.test(text)) {
          fountain += `\n${text.toUpperCase()}\n\n`;
        } else {
          fountain += `\n.${text.toUpperCase()}\n\n`;
        }
      } else if (line.includes('screenplay-character')) {
        // Character cue: uppercase, indented in Fountain by @prefix or just uppercase
        fountain += `${text.toUpperCase()}\n`;
      } else if (line.includes('screenplay-parenthetical')) {
        // Parenthetical: wrapped in parens
        const clean = text.replace(/^\(|\)$/g, '');
        fountain += `(${clean})\n`;
      } else if (line.includes('screenplay-dialogue')) {
        // Dialogue: just text after character
        fountain += `${text}\n\n`;
      } else if (line.includes('screenplay-transition')) {
        // Transition: must end with TO: or force with >
        if (text.toUpperCase().endsWith('TO:') || text.toUpperCase() === 'FADE OUT.') {
          fountain += `\n${text.toUpperCase()}\n\n`;
        } else {
          fountain += `\n> ${text.toUpperCase()}\n\n`;
        }
      } else if (line.includes('screenplay-action')) {
        // Action: plain text
        fountain += `${text}\n\n`;
      } else {
        // Fallback: treat as action
        fountain += `${text}\n\n`;
      }
    }
  }

  return Buffer.from(fountain, 'utf-8');
}

function escapeHtml(str: string): string {
  return str
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}
